/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package crypto;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
@EnableScheduling
public class App {
    @RequestMapping("/")
    public String getHealth() {

        return "OK";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
